# Generated by Django 5.0.4 on 2024-07-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('validity_period', models.CharField(max_length=4)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cash',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('salary', 'MAOSH'), ('gift', "SOVG'A")], max_length=10)),
                ('payment_type', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD'), ('currency', 'CURRENCY')], max_length=10)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('komunal', 'KOMUNAL'), ('shaxsiy', 'SHAXSIY'), ('transport', 'TRANSPORT'), ('uyali aloqa', 'UYALI ALOQA'), ('internet', 'INTERNET'), ("ro'zg'or", "RO'ZG'OR")], max_length=15)),
                ('payment_type', models.CharField(choices=[('cash', 'CASH'), ('card', 'CARD'), ('currency', 'CURRENCY')], max_length=10)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcomes',
            },
        ),
    ]
