# Generated by Django 5.0.4 on 2024-07-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income',
            table='incomes',
        ),
    ]
